version: "3.9"

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.1
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HTTP_ENABLED=true
      - KC_PROXY=edge
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import/realm-adduser-realm.json
    command: ["start-dev", "--import-realm"]
    volumes:
      - ./realm:/opt/keycloak/data/import
    restart: unless-stopped
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge